%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%

function [result] = xcorr_cst(IQsamples, CAcode)

    % determine the lengths of both sequences
    n_IQsamples = numel(IQsamples);
    n_CAcode = numel(CAcode);

    % correlate both sequences
    result = xcorr(IQsamples,CAcode);
    
    % remove the transient part generated by Matlab
    result = result(n_IQsamples : end-(n_CAcode-1));               
end
